labels: [ "type: feature" ]

body:
  - type: markdown
    attributes:
      value: |
        It is recommended that you search all open discussions to avoid duplicate feature requests. If one exists, Please reply to that one if you have anything to add.
        
  - type: textarea
    id: feature
    attributes:
      label: Describe the feature
      description: "A clear and concise description of what the feature is."
      placeholder: "I want a pony for Christmas!"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other
      description: "Add any other context or screenshots about the feature request below."
    validations:
      required: false